name: Test Math Library

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Test Library
      id: test
      run: npm run test
    - name: Time badge
      uses: emibcn/badge-action@v2.0.2
      with:
        label: 'Test coverage'
        status: '53.4%'
        color: 'blue,555,daf'
        path: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Firefox_logo%2C_2019.svg'
            