name: Test Math Library

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Test Library
      id: test
      run: npm run test
    - id: date
      run: echo "##[set-output name=data;]$(date)"
    - name: Time badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: custom
        ICON: 'https://raw.githubusercontent.com/RubbaBoy/BYOBTest/master/icons/dollar.svg'
        STATUS: 'Custom Icons'
        COLOR: red
            