name: Test Math Library

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Test Library
      id: test
      run: npm run test
      uses: RubbaBoy/BYOB@v1.3.0
      with:
          NAME: math
          ICON: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Icon_Mathematical_Plot.svg'
          LABEL: 'Does Really Advanced Math'
          STATUS: ${{ steps.test.outputs.data }}
          COLOR: 007982
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            